### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by bonustrack** [byteball/byteball-witness#3]
I'm not able to run a witness in production. I got stuck with the following error few seconds after starting the node:
```
/home/node/byteball-witness/node_modules/byteballcore/headers_commission.js:91
								var next_mc_unit_props = storage.assocStableUnitsByMci[parent.main_chain_index+1].find(function(props){return props.is_on_main_chain});
						
TypeError: Cannot read property 'find' of undefined
    at /home/node/byteball-witness/node_modules/byteballcore/headers_commission.js:91:91
    at Array.forEach (<anonymous>)
    at /home/node/byteball-witness/node_modules/byteballcore/headers_commission.js:89:22
    at Statement.<anonymous> (/home/node/byteball-witness/node_modules/byteballcore/sqlite_pool.js:115:6)
```
See related code in `byteballcore` :
https://github.com/byteball/byteballcore/blob/master/headers_commission.js#L91

Any idea how to solve this?

**Comment by Sekhmet** [comment]
I don't think it's problem specific to byteball-witness. I had the same problem with Windows full wallet (2.4.1):
![obraz](https://user-images.githubusercontent.com/1968722/42882106-c9e6e4d0-8a98-11e8-9327-c95d7021eefe.png)

It has been syncing at 0% for a while and then crashed.

**Comment by tonyofbyteball** [comment]
Fixed in https://github.com/byteball/byteballcore/commit/9f3bcff7cfbbe680b4985d8e489b5eee859a27af
